### ISSUE TITLE
Efficiency in reading translation

### ISSUE THREAD

**Issue by fnielsen** [urbanecm/flask-jsonlocale#1]
As far as I can read the code, the translation file is read each time a translation occurs: 
https://github.com/urbanecm/flask-jsonlocale/blob/f02b7eb801b6e43dbaa0f91b2ab3285dd051a05f/flask_jsonlocale.py#L36

That can hardly be efficient? Am I misunderstanding something?

**Comment by urbanecm** [comment]
You're probably right. I'll try to dig into optimalizing when I'll have some more time. Of course, if you have any specific solution in mind, I'll be more than happy if you submit a PR for this. Best, Martin

**Comment by urbanecm** [comment]
Should be fixed with 890fb429dc392795c6e60ce3c37d38e3db34297d and cdbc2456c13ccb9dd72bb621c4164ac24501ff2c

**Comment by urbanecm** [comment]
Released as 1.9. Sorry for creating many releases to do this, this is my first pypi-released library and I was failing to release it correctly.
