### ISSUE TITLE
IOError on uselang with wrong language

### ISSUE THREAD

**Issue by fnielsen** [urbanecm/flask-jsonlocale#2]
`http://127.0.0.1:5000/?uselang=XXXXX` gives `IOError: [Errno 2] No such file or directory`. It should probably fail gracefully.

**Comment by urbanecm** [comment]
Should that a) display a meaningful error message b) fallback to DEFAULT_LANGUAGE? What do you think?

**Comment by fnielsen** [comment]
Fallback

**Comment by urbanecm** [comment]
Done!

**Comment by urbanecm** [comment]
Released as 1.9. Sorry for creating many releases to do this, this is my first pypi-released library and I was failing to release it correctly.
